CREATE TABLE users
(
    id         BINARY(16) PRIMARY KEY,
    full_name  VARCHAR(255) NOT NULL,
    email_id   VARCHAR(255) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);